# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: StartingPoint
    displayName: 'Starting Point'
    jobs:
      - job: job1
        steps:
          - script: echo "Starting"
            displayName: 'Initialize'

  - stage: StageA
    displayName: 'Stage A'
    dependsOn: StartingPoint
    jobs:
      - job: jobA
        steps:
          - script: echo "Execute Stage A..."
            displayName: 'Run Stage A'

  - stage: StageB
    displayName: 'Stage B'
    dependsOn: StartingPoint
    jobs:
      - job: jobB
        steps:
          - script: echo "Execute Stage B..."
            displayName: 'Run Stage B'

  - stage: StageC
    displayName: 'Stage C'
    dependsOn: StartingPoint
    jobs:
      - job: jobC
        steps:
          - script: echo "Execute Stage C..."
            displayName: 'Run Stage C'

  - stage: ProduceArtifact
    displayName: 'Produce Artifact'
    dependsOn:
      - StageA
      - StageB
      - StageC
    jobs:
      - job: jobArtifact
        steps:
          - script: echo "Produce artifact from previous stages..."
            displayName: 'Create Artifact'

  - stage: Deploy
    displayName: 'Deploy Job'
    dependsOn: ProduceArtifact
    condition: succeeded('ProduceArtifact')
    jobs:
      - job: jobDeploy
        steps:
          - script: echo "Deploy the app..."
            displayName: 'Deploy app'
  - stage: rollback
    displayName: 'roll back'
    dependsOn: ProduceArtifact
    condition: failed('ProduceArtifact')
    jobs:
      - job: rollback
        steps:
          - script: echo "rollback app..."
            displayName: 'rollback app'