# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs: 
 - job: job1
   steps:
   - script: echo Hello, world 234!
     displayName: 'Run a one-line script'
     
 - job: job2
   dependsOn: job1
   steps:
   - script: echo Hello, world 34567!
     displayName: 'Run a two-line script'

 - job: job3
   dependsOn: job2
   steps:
   - script: echo Hello, world 7899!
     displayName: 'Run a three-line script'
